language: php
sudo: false
php:
- '5.3'
- '7'
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=wck2016@travis-ci.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=wck2016@travis-ci.org
  - secure: m6x6Mc24+AbxayJPxLtuhF/+9Yn3RnaprWnUXuwii0lMoi2jIepbKs95ljmGncI7OUeeM7Pge++kxGG7NZeT/oKd6mGePhNVIJOQwY3mIzqbEh2g1CZ3vWUbMATze0o1YomXdDVWLXu4kmXxnU+aylkirPCua016FUlFSVYmEFma8QPKLOYnZRhz6S/inxCiwXXAS5RvnMCZU8E9AKOJ2DnF9h/AefX8ZcEVqK0cN3LV92/B9Qq3tVcVK/a77YB5oO0aY89q0gGCCJCIdry+SSmFgRsbAp4flRpiUoMEBqk3qa+Yb9cxGUBHhBb6fsQ1RaWDsdqpF81YggE4FeV7zH63OwT1EcaeLCXWR1uKR1r8+qPnv3oYsPyZMZfF+TxXrY+cQBvPb+0DgScPeUysoJnNScrQ2WGlaTY2Kakhu8Bv+NXue03xKHnrHUxri0pOBSLKFWzq5S1bdVk6QwtwNoo0yvqFkP1wgplOt1Cb42TYWz99MO59jNXAinV5hvQY9VLJLrxZaeR3FL+j7hVNkPoW89VxVSU9ejzVISpQcjZZ6TqPq/E6MgEKu8Mi+f5gDG9M9pvPWyFqufgDjKRNEtGok0LcwlAzAoGjyf4NducLBfhScafhisO9pgWAA61U4S7PJydYHx3YgM92HZ+ktSRHJRbQjcB85mp/guw4/ZQ=
cache:
 directories:
 - node_modules
before_script:
- nvm install 5
- npm install
- npm run build
script:
- ls -al style.css
- ls -al bundle.js
- if find . -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi;
after_success:
- bash ./bin/deploy.sh
notifications:
  slack:
    secure: UtkZimyOy5SUqBc1+IKB9HbcYq+Ym0qdOEqRzUXetUe1UA2Eq4HAPUI4A9bnnp0pFg3Yfd7xWMBcjZV1b/nI2LSbgjzKHFMH5NfAVp6YMjtHG7MWLY0t5gzPiHJ/e+Mj+H2JKcyYleOvX/a7O2McRY+7VPDjBQSudCw+3+NPLCiott68iIR7mW3yfiy91R5IyndAXbDZtAv4ZViaSDHXBHo1WSwHHPB02JjwmblRiY3dqDl7dqHwVQNmHhHAxJB71F16vGSkyi728beL2iIc338l9h0mpK+RpHIGn416wVyu5gOG5z0iCos7PUqU7Lz6cVumSmSOYspAMjtMSo9YWNuA7YMhDimiQdjqSZMECp1Jc0cZSNwsxJSDUrKqQKX2stM3dDpOFGVjYidNLiLA1OI1Hh0mh5NeSEjWefJHoYrP+gVXaaquGKL059/O9HDfMBQaKK4wF+giKY0hQWIcpAPi7lAUlF4+exPcBrsRwjE8GO0smEiVaUki068hby397lH/U6mORxG4pvbNXoSuwRoEMRJk5hyOG1mlMojvGwxD/ifM046TAG2fcMSV0Nsz0IAkC7ITvjEuzx5gCFw3AbjLsX896VblnsGqFbOFmHbknCrYMl54gFp4FyBsVoBFzyVYX1y/gcHJjxTuHoe1wHFbzK4mgp2aHodbeqPHZxA=
